### ISSUE TITLE
v4.0 todo / remember

### ISSUE THREAD

**Issue by poi33** [enonic/lib-menu#35]
- [x] Remove text / displayName / menuName. They all are combined into **title**
- [x] Draft new release
- [x] Change exists into using 7.1 if available (check if exists is set)
- [x] Aria label update

**Comment by tajakobsen** [comment]
The `.active` css-classes can be removed since the same styling can be achieved by using `[aria-current="page"]` or `[aria-current="location"]`as the css-selector.

E.g:
```css
[aria-current="page"] {
  color: blue;
}
```
